dataset_path: ../dataset/PPBEmo_video_data/
path_dataset_train_csv: df_train.csv
path_dataset_val_csv: df_val.csv
path_dataset_test_csv: df_test.csv
saving_dir_experiments: ./save_weight/
saving_dir_model: distillation_model
num_classes: 7
num_epoch: 50
batch_size: 8
num_frames: 64
sampling_rate: 8
frames_per_second: 10
path_torchvideo_model: facebookresearch/pytorchvideo
name_torchvideo_model: slow_r50
learning_rate: 0.001
scheduler_step_size: 3
scheduler_gamma: 0.1
crop_video: 1
freeze_layers: 2
epoch_start_unfreeze: 5
n_nodes: 128
dropout: 0.3
block_start_unfreeze: 4
do_train: 1
do_test: 1